importScripts(
  "background.js",
  "content_bootstrap.js",
  "background_hardening.js",
  "browser_tabs.js",
  "model_routing.js",
  "image_routing.js",
  "voice_routing.js",
  "audio_routing_v2.js",
);
