import assert from "node:assert/strict";
import fs from "node:fs";
const code=fs.readFileSync(new URL("../app/admin_linux_device_authority_v124.js",import.meta.url),"utf8");
const begin=code.indexOf("  // Real physical truth");
const end=code.indexOf("  function renderDevices(){",begin);
assert.ok(begin>=0&&end>begin,"Linux Worker truth functions must exist");
const state={standbyTruth:new Map(),verifiedStandby:new Map()};
let now=100000;
const esc=x=>String(x);
const workerStatus=w=>[w.status==="offline"?"离线":"运行正常",w.status==="offline"?"bad":"good"];
const {updateLinuxStandbyTruth,linuxStandbyCell}=new Function("state","workerStatus","esc","Date",
code.slice(begin,end)+"\nreturn {updateLinuxStandbyTruth,linuxStandbyCell};")(state,workerStatus,esc,{now:()=>now});
const linux=(id,ext)=>({worker_id:id,extension_client_id:ext,enabled:true,status:"ready"});
const w1=linux("wrk_1","ext_1"),w2=linux("wrk_2","ext_2");
const c1={client_id:"ext_1",online:true,connection_enabled:true,metadata:{linux_worker_id:"wrk_1"}};
const c2={client_id:"ext_2",online:true,connection_enabled:true,metadata:{linux_worker_id:"wrk_2"}};
const truth=(id,count,snapshotAt=100)=>({client_id:id,online:true,live_verified:true,chatgpt_routing_ready:true,truth_status:"verified",standby_window_count:count,snapshot_updated_at_ms:snapshotAt});
const payload=(...workers)=>({truth_revision:89,workers});
updateLinuxStandbyTruth(payload(truth("ext_1",3),truth("ext_2",0)));
assert.match(linuxStandbyCell(w1,c1),/data-linux-standby-source="live".*>3<\/span>/);
assert.match(linuxStandbyCell(w2,c2),/data-linux-standby-source="live".*>0<\/span>/);
assert.match(linuxStandbyCell(w1,c2),/data-linux-standby-source="unknown"/,"a different Linux Worker must not borrow another Bridge's count");
now+=2500;
updateLinuxStandbyTruth(payload({client_id:"ext_1",online:true,live_verified:false,chatgpt_routing_ready:true,truth_status:"refresh-timeout",standby_window_count:null},truth("ext_2",1,101)));
assert.match(linuxStandbyCell(w1,c1),/data-linux-standby-source="cached".*>3<\/span>/);
assert.match(linuxStandbyCell(w1,c1),/上次核验/);
assert.match(linuxStandbyCell(w2,c2),/>1<\/span>/);
now+=2000;
updateLinuxStandbyTruth(null);
assert.match(linuxStandbyCell(w1,c1),/上次核验/);
now+=1000;
updateLinuxStandbyTruth(payload(truth("ext_1",2,102)));
assert.match(linuxStandbyCell(w1,c1),/source="live".*>2<\/span>/);
now+=1000;
updateLinuxStandbyTruth(payload(truth("ext_1",3,101)));
assert.match(linuxStandbyCell(w1,c1),/source="cached".*>2<\/span>/,"older snapshot cannot roll count backward");
now+=47000;
updateLinuxStandbyTruth(null);
assert.match(linuxStandbyCell(w1,c1),/source="unknown".*>\?<\/span>/,"stale proof expires");
now+=1000;
updateLinuxStandbyTruth(payload(truth("ext_1",3,103)));
assert.match(linuxStandbyCell({...w1,status:"offline"},c1),/source="unknown"/);
assert.match(linuxStandbyCell(w1,{...c1,online:false}),/source="unknown"/);
assert.match(linuxStandbyCell(w1,{...c1,connection_enabled:false}),/source="unknown"/);
assert.match(linuxStandbyCell({...w1,enabled:false},c1),/source="unknown"/);
now+=1000;
updateLinuxStandbyTruth(payload({...truth("ext_1",null,104),live_verified:false,truth_status:"login-required",chatgpt_routing_ready:false}));
assert.match(linuxStandbyCell(w1,c1),/source="unknown"/,"login loss invalidates cached proof");
now+=1000;
updateLinuxStandbyTruth(payload({...truth("ext_1",null,105)}));
assert.match(linuxStandbyCell(w1,c1),/source="unknown"/,"null is not zero");
console.log("Linux Worker v158 two-bridge physical standby truth cases passed");
