from __future__ import annotations

import json
from pathlib import Path
import subprocess


ROOT = Path(__file__).resolve().parents[1]
EXT = ROOT / "chrome_extension"
MAIN = EXT / "multimodal_main_v78.js"
CONTENT = EXT / "content_multimodal_v78.js"


def test_multimodal_v78_is_split_across_main_and_isolated_worlds() -> None:
    manifest = json.loads((EXT / "manifest.json").read_text(encoding="utf-8"))
    assert manifest["version"] == "0.8.25"
    main = manifest["content_scripts"][0]
    isolated = manifest["content_scripts"][1]
    assert main["world"] == "MAIN"
    assert "multimodal_main_v78.js" in main["js"]
    assert "content_multimodal_v78.js" in isolated["js"]
    assert isolated["js"].index("content_multimodal_v78.js") < isolated["js"].index("content_multimodal_v68.js")
    assert "debugger" not in manifest.get("permissions", [])


def test_main_world_bridge_uses_page_realm_file_and_events() -> None:
    source = MAIN.read_text(encoding="utf-8")
    assert 'const REVISION = 78' in source
    assert 'chat2api.multimodal.main.request.v78' in source
    assert 'chat2api.multimodal.main.response.v78' in source
    assert 'Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, "files")' in source
    assert 'new DataTransfer()' in source
    assert 'new InputEvent("input"' in source
    assert 'new ClipboardEvent("paste"' in source
    assert 'new DragEvent(type' in source
    assert 'data-chat2api-multimodal-main-v78' in source


def test_isolated_multimodal_v78_preserves_confirmation_and_no_duplicate_retry_after_signal() -> None:
    source = CONTENT.read_text(encoding="utf-8")
    assert 'const REVISION = 78' in source
    assert 'const CONTROLLER = "multimodal-main-world-v78"' in source
    assert 'function inferMime' in source
    assert 'async function mainAttempt' in source
    assert 'main-file-input' not in source  # names are generated by the main- prefix at runtime
    assert 'strategies = ["file-input"]' in source
    assert 'strategies.push("composer-paste")' in source
    assert 'strategies.push("composer-drop")' in source
    assert 'if (result.signal) break' in source
    assert 'attachment_main_world_bridge_v78: true' in source
    assert 'attachment_verified: true' in source
    assert 'message.type === "chat2api.attach.prepare.v4"' in source


def test_multimodal_v78_javascript_syntax() -> None:
    for path in (MAIN, CONTENT):
        result = subprocess.run(["node", "--check", str(path)], capture_output=True, text=True)
        assert result.returncode == 0, result.stderr
