(() => {
  const KEY = "__CHAT2API_LINUX_DEVICE_AUTHORITY_V124__";
  if (globalThis[KEY]) return;
  const state = {revision:124, devices:[], pairings:[], proxies:[], health:new Map(), login:{workerId:"",ticket:"",sourceWidth:1920,sourceHeight:1080,timer:0,closing:false}, selectedProxyWorker:"", selectedDevice:""};
  globalThis[KEY] = state;

  const esc = value => String(value ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]);
  const api = async (path, options={}) => {
    const {headers={},body,...rest}=options;
    const response=await fetch(path,{credentials:"same-origin",cache:"no-store",...rest,headers:{"Content-Type":"application/json",...headers},...(body===undefined?{}:{body:typeof body==="string"?body:JSON.stringify(body)})});
    let payload={}; try{payload=await response.json();}catch(_){}
    if(!response.ok) throw new Error(typeof payload.detail==="string"?payload.detail:`HTTP ${response.status}`);
    return payload;
  };
  const beijing = value => { if(!value)return "-"; const d=new Date(value); if(!Number.isFinite(d.getTime()))return "-"; return new Intl.DateTimeFormat("zh-CN",{timeZone:"Asia/Shanghai",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false}).format(d); };
  const bridge = worker => worker?.metadata?.bridge && typeof worker.metadata.bridge==="object" ? worker.metadata.bridge : {};
  const proxySummary = worker => worker?.metadata?.proxy_summary && typeof worker.metadata.proxy_summary==="object" ? worker.metadata.proxy_summary : {};
  const country = code => ({US:"美国",JP:"日本",SG:"新加坡",KR:"韩国",GB:"英国",DE:"德国",FR:"法国",CA:"加拿大",AU:"澳大利亚",HK:"中国香港",TW:"中国台湾",CN:"中国大陆"})[String(code||"").toUpperCase()] || String(code||"").toUpperCase();
  const networkText = worker => { const b=bridge(worker); const s=String(b.network_probe_status||worker?.network_status||"unknown").toLowerCase(); const c=country(b.network_country_code); if(s==="external")return c?`外网（${c}）`:"外网"; if(s==="china-mainland")return "中国大陆网络"; if(s==="offline")return "网络离线"; if(["ready","online","connected","reachable"].includes(s))return "已联网"; return "未检测"; };
  const workerStatus = worker => { if(!worker)return ["待安装","warn"]; if(worker.revoked_at)return ["已禁用","bad"]; const seen=worker.last_seen_at?new Date(worker.last_seen_at).getTime():0; if(seen&&Date.now()-seen>45000)return ["离线","bad"]; const map={ready:["运行正常","good"],waiting_proxy:["待配置代理","warn"],proxy_checking:["检测代理","warn"],waiting_login:["待登录","warn"],login_checking:["检测登录","warn"],degraded:["运行异常","bad"],offline:["离线","bad"],error:["错误","bad"],enrolling:["注册中","warn"]}; return map[String(worker.status||"").toLowerCase()]||[String(worker.status||"未知"),"warn"]; };
  const chatgpt = worker => { if(!worker)return "-"; const b=bridge(worker); return String(worker.chatgpt_status||"").toLowerCase()==="ready" || (String(b.login_state||"").toLowerCase()==="ready"&&b.composer_ready===true) ? "已登录":"未登录"; };
  const proxyView = worker => { if(!worker)return {main:"-",sub:"等待设备安装",tone:"warn"}; const p=proxySummary(worker); const name=String(worker?.metadata?.proxy_catalog_name||p.name||p.server||p.protocol||"直连"); const health=state.health.get(String(worker.worker_id||"")); const net=networkText(worker); if(!health)return {main:`${name} · ${net}`,sub:"点击 ⚙ 可切换代理或测试当前代理",tone:"warn"}; const n=health.networkReady?"网络正常":"网络异常"; const g=health.chatReady?"GPT正常":"GPT异常"; const l=health.latencyMs?`${health.latencyMs} ms`:"--"; return {main:`${name} · ${net}`,sub:`${n} · ${g} · 延迟 ${l}`,tone:health.networkReady&&health.chatReady?"good":"bad"}; };
  const primary = device => Array.isArray(device?.workers) ? device.workers.find(w=>Number(w.worker_slot||1)===1)||device.workers[0] : null;

  function buildShell(){
    const nav=document.querySelector(".nav"), content=document.querySelector(".content");
    if(!nav||!content){setTimeout(buildShell,100);return;}
    document.getElementById("view-linux-workers")?.remove();
    [...nav.querySelectorAll("button")].filter(b=>String(b.textContent||"").trim()==="Linux Worker").forEach(b=>b.remove());
    const button=document.createElement("button"); button.dataset.view="linux-workers"; button.textContent="Linux Worker"; nav.appendChild(button);
    const section=document.createElement("section"); section.className="view"; section.id="view-linux-workers"; section.dataset.authority="v124";
    section.innerHTML=`<div class="panel"><h3 style="margin:0 0 12px">设备列表</h3><div class="toolbar"><button class="action good" id="createLinuxDeviceV124">新增设备</button><button class="action" id="proxyManagerV124">代理管理</button><button class="action good" id="manageDeviceWorkersV124">管理设备 Worker</button><button class="action" id="refreshLinuxDevicesV124">刷新</button><button class="action danger" id="purgeLegacyLinuxV124" style="display:none">清理旧 Linux 数据</button></div><div id="linuxDeviceSummaryV124" style="margin:10px 0;color:#94a3b8;font-size:12px"></div><div class="scroll"><table id="linuxDeviceTableV124"><thead><tr><th>设备名称</th><th>状态</th><th>安装进度</th><th>安装命令</th><th>系统</th><th>代理</th><th>ChatGPT</th><th>最后更新</th><th>操作</th></tr></thead><tbody id="linuxDeviceRowsV124"></tbody></table></div></div>`;
    content.insertBefore(section,content.lastElementChild);
    const style=document.createElement("style"); style.textContent=`#linuxDeviceTableV124{min-width:1160px;width:100%;border-collapse:separate;border-spacing:0}#linuxDeviceTableV124 th,#linuxDeviceTableV124 td{padding:10px 11px;vertical-align:middle;border-bottom:1px solid rgba(71,85,105,.32)}#linuxDeviceTableV124 th{text-align:left;white-space:nowrap;color:#a9b7ca;font-size:12px}.v124-pill{display:inline-flex;align-items:center;min-height:22px;padding:2px 8px;border:1px solid #334155;border-radius:999px;background:#101a2b;font-size:12px;white-space:nowrap}.v124-pill.good{border-color:#166534;background:rgba(20,83,45,.22)}.v124-pill.warn{border-color:#854d0e;background:rgba(113,63,18,.24)}.v124-pill.bad{border-color:#991b1b;background:rgba(127,29,29,.22)}.v124-muted{color:#94a3b8;font-size:12px;line-height:1.4}.v124-proxy-main{display:flex;align-items:center;gap:5px;white-space:nowrap}.v124-gear{display:inline-grid;place-items:center;width:24px;height:24px;padding:0;border:1px solid #334155;border-radius:6px;background:#17233a;color:#cbd5e1;cursor:pointer}.v124-actions{display:flex;gap:6px;flex-wrap:wrap;min-width:300px}.v124-dialog{width:min(760px,calc(100vw - 28px));max-width:none;border:1px solid #334155;border-radius:12px;background:#0f172a;color:#e5e7eb;padding:0;box-shadow:0 24px 90px rgba(0,0,0,.65)}.v124-dialog select,.v124-dialog input,.v124-dialog textarea{box-sizing:border-box;width:100%;padding:9px 10px;border:1px solid #334155;border-radius:8px;background:#020617;color:#e5e7eb}`; document.head.appendChild(style);
    installDialogs(); installEvents(button,section); renamePairingHeader(); refreshAll(true);
    if(location.hash==="#linux-workers")button.click();
  }

  function dialog(id,title,body){const d=document.createElement("dialog");d.id=id;d.className="v124-dialog";d.innerHTML=`<div style="padding:20px"><div style="display:flex;justify-content:space-between;gap:12px;align-items:start"><div><div style="font-size:18px;font-weight:700">${title}</div></div><button class="action" data-close-dialog="${id}">关闭</button></div>${body}</div>`;document.body.appendChild(d);return d;}
  function installDialogs(){
    dialog("linuxDeviceCreateV124","新增 Linux 设备",`<div class="v124-muted" style="margin-top:6px">先选择配对码和代理，再生成安装命令。设备名称唯一取自配对码的设备名称。</div><label style="display:block;margin-top:15px">配对码 / 设备名称<select id="devicePairingV124" style="margin-top:6px"></select></label><label style="display:block;margin-top:12px">代理<select id="deviceProxyV124" style="margin-top:6px"></select></label><div id="deviceCreateResultV124" class="v124-muted" style="margin-top:10px;min-height:20px"></div><div id="deviceCommandBoxV124" style="display:none;margin-top:10px;padding:10px;border:1px solid #334155;border-radius:8px;background:#020617"><code id="deviceCommandV124" style="word-break:break-all;white-space:normal"></code><div style="margin-top:8px"><button class="action" id="copyDeviceCommandV124">复制命令</button></div></div><div style="display:flex;justify-content:flex-end;margin-top:14px"><button class="action good" id="generateDeviceV124">生成安装命令</button></div>`);
    dialog("linuxProxyManagerV124","代理管理",`<div id="proxyListV124" style="margin-top:14px"></div><div style="margin-top:14px;padding-top:12px;border-top:1px solid #334155"><input id="proxyNameV124" placeholder="代理名称"><textarea id="proxyLinkV124" rows="3" placeholder="vless://、vmess://、trojan:// 或 ss://" style="margin-top:8px"></textarea><button class="action good" id="addProxyV124" style="margin-top:8px">添加代理</button></div>`);
    dialog("linuxWorkerManagerV124","设备 Worker 管理",`<div style="display:flex;gap:8px;align-items:center;margin-top:14px"><select id="managerDeviceV124" style="max-width:360px"></select><button class="action" id="refreshManagerV124">刷新</button><button class="action good" id="openAddWorkerV124">增加 Worker</button></div><div id="managerWorkersV124" style="margin-top:12px"></div><div id="managerCommandV124" style="margin-top:12px"></div>`);
    dialog("linuxAddWorkerV124","增加 Worker",`<div class="v124-muted" style="margin-top:6px">每个 Worker 使用独立配对码、代理和 Chrome Profile；配对码的设备名称必须与当前设备一致。</div><label style="display:block;margin-top:14px">配对码<select id="slotPairingV124" style="margin-top:6px"></select></label><label style="display:block;margin-top:12px">代理<select id="slotProxyV124" style="margin-top:6px"></select></label><div id="slotResultV124" class="v124-muted" style="margin-top:10px"></div><button class="action good" id="generateSlotV124" style="margin-top:12px">生成 Worker 安装命令</button>`);
    dialog("linuxProxyQuickV124","代理设置",`<select id="quickProxyV124" style="margin-top:14px"></select><div style="display:flex;gap:8px;margin-top:9px"><button class="action good" id="applyQuickProxyV124">应用</button><button class="action" id="testQuickProxyV124">测试</button></div><div id="quickProxyResultV124" class="v124-muted" style="margin-top:8px"></div>`);
    const login=dialog("linuxWorkerLoginDialog","远程登录 ChatGPT",`<div id="linuxLoginWorkerName" class="v124-muted" style="margin-top:4px"></div><div style="display:flex;justify-content:space-between;align-items:center;margin:8px 0"><span id="linuxLoginStatus" class="v124-muted">准备中…</span><button class="action" id="closeLinuxLogin">结束登录</button></div><div id="linuxLoginViewport" style="position:relative;background:#000;border:1px solid #334155;border-radius:8px;overflow:hidden;min-height:360px;display:flex;align-items:center;justify-content:center"><img id="linuxLoginFrame" draggable="false" style="display:block;max-width:100%;max-height:calc(100vh - 230px);user-select:none"><textarea id="linuxLoginKeyboardSink" style="position:absolute;left:-10000px;top:0;width:1px;height:1px;opacity:0"></textarea><div id="linuxLoginPlaceholder" style="position:absolute;color:#94a3b8">正在连接 Worker 画面…</div></div>`); login.style.width="min(1320px,calc(100vw - 24px))";
  }

  async function loadOptions(){const o=await api("/api/admin/linux-devices/setup-options");state.pairings=Array.isArray(o.pairing_codes)?o.pairing_codes:[];state.proxies=Array.isArray(o.proxies)?o.proxies:[];}
  function availablePairings(name=""){return state.pairings.filter(p=>p.enabled&&!p.paired&&(!name||String(p.device_name||"")===name));}
  function fillSelect(node,items,valueKey,label){node.innerHTML=items.length?items.map(x=>`<option value="${esc(x[valueKey])}">${esc(label(x))}</option>`).join(""):'<option value="">暂无可选项</option>';}

  async function refreshAll(force=false){
    try{const [devices,legacy]=await Promise.all([api("/api/admin/linux-devices"),api("/api/admin/linux-devices/legacy-records")]);state.devices=Array.isArray(devices.data)?devices.data:[];renderDevices();renderManager();const count=Number(legacy.worker_count||0)+Number(legacy.installation_count||0);const purge=document.getElementById("purgeLegacyLinuxV124");if(purge){purge.style.display=count?"":"none";purge.textContent=count?`清理旧 Linux 数据（${count}）`:"清理旧 Linux 数据";}}
    catch(error){const body=document.getElementById("linuxDeviceRowsV124");if(body)body.innerHTML=`<tr><td colspan="9">${esc(error.message)}</td></tr>`;}
  }
  function renderDevices(){const body=document.getElementById("linuxDeviceRowsV124");if(!body)return;let online=0;body.innerHTML=state.devices.map((d,i)=>{const w=primary(d);const [status,tone]=workerStatus(w);if(tone==="good")online++;const proxy=proxyView(w);const cmd=d.install_command&&!w?`<button class="action" data-copy-device="${i}">复制</button>`:"-";const system=w?(String(w.os_version||"").match(/ubuntu/i)?"Ubuntu":esc(String(w.platform||"Linux"))):"-";const updated=w?.last_seen_at||d.install_updated_at||d.install_created_at;return `<tr><td><b>${esc(d.device_name)}</b><div class="v124-muted">${d.worker_count||0} Worker</div></td><td><span class="v124-pill ${tone}">${esc(status)}</span></td><td class="v124-muted">${esc(d.install_message||d.install_stage||d.install_state||"-")}</td><td>${cmd}</td><td>${system}</td><td><div class="v124-proxy-main"><span class="v124-pill ${proxy.tone}">${esc(proxy.main)}</span>${w?`<button class="v124-gear" data-proxy-worker="${esc(w.worker_id)}" data-device="${i}">⚙</button>`:""}</div><div class="v124-muted">${esc(proxy.sub)}</div></td><td>${esc(chatgpt(w))}</td><td class="v124-muted">${esc(beijing(updated))}</td><td><div class="v124-actions">${w?`<button class="action" data-worker-action="upgrade" data-worker="${esc(w.worker_id)}">更新</button><button class="action" data-worker-action="initialize" data-worker="${esc(w.worker_id)}">初始化</button><button class="action" data-login-worker="${esc(w.worker_id)}" data-name="${esc(d.device_name)}">登录</button><button class="action" data-diagnostics="${esc(w.worker_id)}">诊断日志</button>`:""}<button class="action danger" data-delete-device="${esc(d.device_id)}">彻底删除设备</button></div></td></tr>`;}).join("")||'<tr><td colspan="9" class="v124-muted">暂无新版 Linux 设备。请点击“新增设备”重新安装。</td></tr>';const summary=document.getElementById("linuxDeviceSummaryV124");if(summary)summary.textContent=`设备：${state.devices.length} · Worker：${state.devices.reduce((n,d)=>n+Number(d.worker_count||0),0)} · 在线设备：${online}`;}

  function renderManager(){const select=document.getElementById("managerDeviceV124"),box=document.getElementById("managerWorkersV124");if(!select||!box)return;const current=select.value;select.innerHTML=state.devices.map(d=>`<option value="${esc(d.device_id)}">${esc(d.device_name)} · ${d.worker_count||0} Worker</option>`).join("")||'<option value="">暂无设备</option>';if(current&&state.devices.some(d=>d.device_id===current))select.value=current;const d=state.devices.find(x=>x.device_id===select.value)||state.devices[0];state.selectedDevice=d?.device_id||"";if(!d){box.innerHTML='<div class="v124-muted">暂无设备</div>';return;}box.innerHTML=`<table style="width:100%"><thead><tr><th>Worker</th><th>状态</th><th>代理</th><th>ChatGPT</th><th>Extension</th><th>操作</th></tr></thead><tbody>${(d.workers||[]).map(w=>{const [s,t]=workerStatus(w);return `<tr><td><b>Worker ${Number(w.worker_slot||1)}</b></td><td><span class="v124-pill ${t}">${esc(s)}</span></td><td>${esc(String(w.metadata?.proxy_catalog_name||proxySummary(w).name||"-"))}</td><td>${esc(chatgpt(w))}</td><td>${w.extension_client_id?"已连接":"未连接"}</td><td><button class="action" data-login-worker="${esc(w.worker_id)}" data-name="${esc(d.device_name)} · Worker ${Number(w.worker_slot||1)}">登录</button> <button class="v124-gear" data-proxy-worker="${esc(w.worker_id)}">⚙</button></td></tr>`;}).join("")}</tbody></table>`;const pending=(d.slot_installations||[]).filter(x=>!x.worker_id&&x.command);const command=document.getElementById("managerCommandV124");if(command)command.innerHTML=pending.map(x=>`<div style="margin-top:8px;padding:10px;border:1px solid #334155;border-radius:8px"><b>Worker ${x.slot} 待执行安装命令</b><div style="margin-top:6px"><code style="word-break:break-all">${esc(x.command)}</code></div><button class="action" data-copy-text="${esc(x.command)}" style="margin-top:7px">复制</button></div>`).join("");}

  function renamePairingHeader(){const body=document.getElementById("pairingBody");const first=body?.closest("table")?.querySelector("thead th:first-child");if(first)first.textContent="设备名称";}
  async function openCreate(){await loadOptions();fillSelect(document.getElementById("devicePairingV124"),availablePairings(),"pairing_id",p=>`${p.device_name} · ${p.prefix}`);fillSelect(document.getElementById("deviceProxyV124"),state.proxies,"proxy_id",p=>p.name||p.proxy_id);document.getElementById("deviceCreateResultV124").textContent="";document.getElementById("deviceCommandBoxV124").style.display="none";document.getElementById("linuxDeviceCreateV124").showModal();}
  async function openProxyManager(){await loadOptions();renderProxyManager();document.getElementById("linuxProxyManagerV124").showModal();}
  function renderProxyManager(){const box=document.getElementById("proxyListV124");box.innerHTML=state.proxies.map(p=>`<div style="display:flex;justify-content:space-between;gap:10px;align-items:center;padding:8px 0;border-bottom:1px solid #334155"><div><b>${esc(p.name)}</b><div class="v124-muted">${esc(p.scheme||"")}</div></div><button class="action danger" data-delete-proxy="${esc(p.proxy_id)}">删除</button></div>`).join("")||'<div class="v124-muted">暂无代理</div>';}

  async function openProxy(workerId){state.selectedProxyWorker=workerId;await loadOptions();fillSelect(document.getElementById("quickProxyV124"),state.proxies,"proxy_id",p=>p.name||p.proxy_id);document.getElementById("quickProxyResultV124").textContent="";document.getElementById("linuxProxyQuickV124").showModal();}
  async function testWorker(workerId){const result=await api(`/api/admin/linux-workers/${encodeURIComponent(workerId)}/proxy/test`,{method:"POST",body:{}});return {networkReady:result.ok===true,chatReady:result.ok===true,latencyMs:Number(result.latency_ms||0),error:String(result.error||"")};}

  function loginHeaders(){return {"X-Chat2API-Login-Ticket":state.login.ticket};}
  function loginStatus(text){const n=document.getElementById("linuxLoginStatus");if(n)n.textContent=text;}
  function loginPoint(event){const image=document.getElementById("linuxLoginFrame"),r=image.getBoundingClientRect();if(!r.width||!r.height)return null;return {x:Math.round((event.clientX-r.left)/r.width*state.login.sourceWidth),y:Math.round((event.clientY-r.top)/r.height*state.login.sourceHeight)};}
  async function fetchFrame(){if(!state.login.workerId||!state.login.ticket||state.login.closing||!document.getElementById("linuxWorkerLoginDialog").open)return;try{const r=await api(`/api/admin/linux-workers/${encodeURIComponent(state.login.workerId)}/login-session/frame`,{headers:loginHeaders()});if(r.complete){loginStatus("ChatGPT 已登录 · Composer 已就绪");setTimeout(closeLogin,650);refreshAll(true);return;}state.login.sourceWidth=Number(r.source_width||1920);state.login.sourceHeight=Number(r.source_height||1080);const img=document.getElementById("linuxLoginFrame");img.src=`data:${r.mime||"image/jpeg"};base64,${r.frame}`;document.getElementById("linuxLoginPlaceholder").style.display="none";loginStatus("已连接 · 点击画面后可输入");state.login.timer=setTimeout(fetchFrame,850);}catch(e){loginStatus(e.message);state.login.timer=setTimeout(fetchFrame,1800);}}
  async function openLogin(workerId,name){const r=await api(`/api/admin/linux-workers/${encodeURIComponent(workerId)}/login-session`,{method:"POST",body:{}});state.login={workerId,ticket:String(r.ticket||""),sourceWidth:Number(r.source_width||1920),sourceHeight:Number(r.source_height||1080),timer:0,closing:false};document.getElementById("linuxLoginWorkerName").textContent=name||workerId;document.getElementById("linuxLoginPlaceholder").style.display="block";document.getElementById("linuxWorkerLoginDialog").showModal();loginStatus("代理已验证 · 正在连接");fetchFrame();}
  async function closeLogin(){if(state.login.closing)return;state.login.closing=true;if(state.login.timer)clearTimeout(state.login.timer);const {workerId,ticket}=state.login;state.login.ticket="";if(workerId&&ticket){try{await api(`/api/admin/linux-workers/${encodeURIComponent(workerId)}/login-session`,{method:"DELETE",headers:{"X-Chat2API-Login-Ticket":ticket}});}catch(_){}}document.getElementById("linuxLoginFrame").removeAttribute("src");document.getElementById("linuxWorkerLoginDialog").close();state.login={workerId:"",ticket:"",sourceWidth:1920,sourceHeight:1080,timer:0,closing:false};}

  function installEvents(button,section){
    button.onclick=()=>{document.querySelectorAll(".view").forEach(n=>n.classList.remove("active"));document.querySelectorAll(".nav button").forEach(n=>n.classList.toggle("active",n===button));section.classList.add("active");const title=document.getElementById("pageTitle");if(title)title.textContent="Linux Worker";location.hash="linux-workers";refreshAll(true);};
    document.addEventListener("click",async event=>{const t=event.target?.closest?.("button");if(!t)return;try{
      if(t.dataset.closeDialog){document.getElementById(t.dataset.closeDialog)?.close();return;}
      if(t.id==="createLinuxDeviceV124"){await openCreate();return;} if(t.id==="proxyManagerV124"){await openProxyManager();return;} if(t.id==="manageDeviceWorkersV124"){renderManager();document.getElementById("linuxWorkerManagerV124").showModal();return;} if(t.id==="refreshLinuxDevicesV124"||t.id==="refreshManagerV124"){await refreshAll(true);return;}
      if(t.id==="generateDeviceV124"){const r=await api("/api/admin/linux-devices",{method:"POST",body:{pairing_id:document.getElementById("devicePairingV124").value,proxy_id:document.getElementById("deviceProxyV124").value}});document.getElementById("deviceCommandV124").textContent=r.install_command||"";document.getElementById("deviceCommandBoxV124").style.display="block";document.getElementById("deviceCreateResultV124").textContent=`设备「${r.device_name}」已预留。`;await refreshAll(true);return;}
      if(t.id==="copyDeviceCommandV124"){await navigator.clipboard.writeText(document.getElementById("deviceCommandV124").textContent||"");return;} if(t.dataset.copyDevice!==undefined){const d=state.devices[Number(t.dataset.copyDevice)];if(d?.install_command)await navigator.clipboard.writeText(d.install_command);return;} if(t.dataset.copyText){await navigator.clipboard.writeText(t.dataset.copyText);return;}
      if(t.id==="addProxyV124"){await api("/api/admin/linux-worker-proxies",{method:"POST",body:{name:document.getElementById("proxyNameV124").value,share_link:document.getElementById("proxyLinkV124").value}});document.getElementById("proxyNameV124").value="";document.getElementById("proxyLinkV124").value="";await loadOptions();renderProxyManager();return;} if(t.dataset.deleteProxy){if(confirm("确定删除这个代理？")){await api(`/api/admin/linux-worker-proxies/${encodeURIComponent(t.dataset.deleteProxy)}`,{method:"DELETE"});await loadOptions();renderProxyManager();}return;}
      if(t.dataset.proxyWorker){await openProxy(t.dataset.proxyWorker);return;} if(t.id==="applyQuickProxyV124"){const p=state.proxies.find(x=>x.proxy_id===document.getElementById("quickProxyV124").value);if(!p)return;const out=document.getElementById("quickProxyResultV124");out.textContent="正在应用代理…";await api(`/api/admin/linux-workers/${encodeURIComponent(state.selectedProxyWorker)}/proxy`,{method:"POST",body:{share_link:p.share_link}});await api(`/api/admin/linux-workers/${encodeURIComponent(state.selectedProxyWorker)}/proxy-label`,{method:"POST",body:{name:p.name}}).catch(()=>null);out.textContent="代理已应用";state.health.delete(state.selectedProxyWorker);await refreshAll(true);return;} if(t.id==="testQuickProxyV124"){const out=document.getElementById("quickProxyResultV124");out.textContent="测试中…";const h=await testWorker(state.selectedProxyWorker);state.health.set(state.selectedProxyWorker,h);out.textContent=h.networkReady?"当前代理可达":"当前代理不可达";renderDevices();return;}
      if(t.dataset.workerAction){const id=t.dataset.worker;if(t.dataset.workerAction==="upgrade")await api(`/api/admin/linux-workers/${encodeURIComponent(id)}/upgrade`,{method:"POST",body:{}});else await api(`/api/admin/linux-workers/${encodeURIComponent(id)}/initialize`,{method:"POST",body:{}});await refreshAll(true);return;} if(t.dataset.loginWorker){await openLogin(t.dataset.loginWorker,t.dataset.name);return;} if(t.dataset.diagnostics){const response=await fetch(`/api/admin/linux-worker/${encodeURIComponent(t.dataset.diagnostics)}/diagnostics/logs`,{credentials:"same-origin",cache:"no-store"});if(!response.ok)throw new Error(await response.text());const blob=await response.blob(),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`chat2api-worker-${t.dataset.diagnostics}-diagnostics.zip`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1200);return;}
      if(t.dataset.deleteDevice){if(confirm("确定彻底删除此 Linux 设备的中心端 Worker/安装记录？请确认目标 Linux 主机已经卸载。")){await api(`/api/admin/linux-devices/${encodeURIComponent(t.dataset.deleteDevice)}`,{method:"DELETE"});await refreshAll(true);}return;}
      if(t.id==="purgeLegacyLinuxV124"){if(confirm("这会彻底删除旧 Linux Worker/安装记录，不迁移、不兼容。确认旧主机已经卸载？")){await api("/api/admin/linux-devices/legacy-records",{method:"DELETE",body:{confirm:"PURGE_LEGACY_LINUX"}});await refreshAll(true);}return;}
      if(t.id==="openAddWorkerV124"){const d=state.devices.find(x=>x.device_id===document.getElementById("managerDeviceV124").value);if(!d)throw new Error("请先选择设备");await loadOptions();fillSelect(document.getElementById("slotPairingV124"),availablePairings(d.device_name),"pairing_id",p=>`${p.device_name} · ${p.prefix}`);fillSelect(document.getElementById("slotProxyV124"),state.proxies,"proxy_id",p=>p.name||p.proxy_id);document.getElementById("slotResultV124").textContent="";document.getElementById("linuxAddWorkerV124").showModal();return;} if(t.id==="generateSlotV124"){const d=document.getElementById("managerDeviceV124").value;const r=await api(`/api/admin/linux-devices/${encodeURIComponent(d)}/workers`,{method:"POST",body:{pairing_id:document.getElementById("slotPairingV124").value,proxy_id:document.getElementById("slotProxyV124").value}});document.getElementById("slotResultV124").textContent=`Worker ${r.worker_slot} 安装命令已生成`;document.getElementById("linuxAddWorkerV124").close();await refreshAll(true);return;}
      if(t.id==="closeLinuxLogin"){await closeLogin();return;}
    }catch(error){alert(error.message||String(error));}},true);
    document.getElementById("managerDeviceV124").addEventListener("change",renderManager);
    const img=document.getElementById("linuxLoginFrame"),sink=document.getElementById("linuxLoginKeyboardSink");img.addEventListener("click",e=>{sink.focus({preventScroll:true});const p=loginPoint(e);if(p&&state.login.ticket)api(`/api/admin/linux-workers/${encodeURIComponent(state.login.workerId)}/login-session/input`,{method:"POST",headers:loginHeaders(),body:{kind:"mouse",action:"click",button:1,...p}}).catch(()=>{});});sink.addEventListener("keydown",e=>{if(!state.login.ticket)return;const modifiers=[];if(e.ctrlKey)modifiers.push("ctrl");if(e.altKey)modifiers.push("alt");if(e.shiftKey)modifiers.push("shift");if(e.metaKey)modifiers.push("super");const special=new Set(["Enter","Tab","Escape","Backspace","Delete","ArrowLeft","ArrowRight","ArrowUp","ArrowDown","Home","End","PageUp","PageDown"," "]);if(e.key.length!==1&&!special.has(e.key))return;e.preventDefault();api(`/api/admin/linux-workers/${encodeURIComponent(state.login.workerId)}/login-session/input`,{method:"POST",headers:loginHeaders(),body:{kind:"key",key:e.key,modifiers}}).catch(err=>loginStatus(err.message));});
    setInterval(()=>{if(section.classList.contains("active")&&!document.querySelector("dialog[open]"))refreshAll();},3000);
    const baseShow=globalThis.show;if(typeof baseShow==="function"&&!baseShow.__linuxDeviceV124){const wrapped=async(...args)=>{const r=await baseShow(...args);if(String(args[0]||"")==="extensions")setTimeout(renamePairingHeader,0);return r;};wrapped.__linuxDeviceV124=true;globalThis.show=wrapped;}
  }

  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",buildShell,{once:true});else buildShell();
})();