(() => {
  const VERSION = "0.22.92-worker-list-v68";
  const COLUMN_SCHEMA_REVISION = 68;
  const STORAGE_KEY = "chat2api.extensionColumns.v3";
  const LEGACY_STORAGE_KEY = "chat2api.extensionColumns.v2";
  const COLUMNS = [
    {key: "client_id", label: "Worker ID"}, {key: "device_id", label: "设备标识"}, {key: "version", label: "版本"},
    {key: "account_type", label: "账户类型"}, {key: "status", label: "状态"}, {key: "worker_settings", label: "并发设置"},
    {key: "last_seen", label: "最后在线"}, {key: "network", label: "网络"}, {key: "chatgpt", label: "ChatGPT"},
    {key: "actions", label: "操作"}, {key: "device_name", label: "设备名称"}, {key: "occupancy", label: "当前占用"},
  ];
  const KNOWN_KEYS=new Set(COLUMNS.map(x=>x.key)),DEFAULT_ORDER=COLUMNS.map(x=>x.key),LEGACY_KEY_MAP=new Map([["platform","worker_settings"]]);
  const REMOVED_KEYS=new Set(["concurrency","reserve_windows","bound_api_keys","occupied_windows"]);
  let prefs=null,menuOpen=false,bodyOverflowBeforeModal="",renderInFlight=null,extensionSnapshot=null,canonicalizing=false,repairQueued=false;
  const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#39;");
  function defaultPrefs(){return{order:[...DEFAULT_ORDER],visible:Object.fromEntries(DEFAULT_ORDER.map(k=>[k,true]))};}
  function normalizePrefs(raw){const r=defaultPrefs(),o=[],s=new Set();for(const original of Array.isArray(raw?.order)?raw.order:[]){if(REMOVED_KEYS.has(original))continue;const k=LEGACY_KEY_MAP.get(original)||original;if(!KNOWN_KEYS.has(k)||s.has(k))continue;s.add(k);o.push(k);}for(const k of DEFAULT_ORDER)if(!s.has(k))o.push(k);r.order=o;if(raw?.visible&&typeof raw.visible==="object")for(const[original,v]of Object.entries(raw.visible)){if(typeof v!=="boolean"||REMOVED_KEYS.has(original))continue;const k=LEGACY_KEY_MAP.get(original)||original;if(KNOWN_KEYS.has(k))r.visible[k]=v;}return r;}
  function loadPrefs(){if(prefs)return prefs;try{const c=localStorage.getItem(STORAGE_KEY);if(c)return prefs=normalizePrefs(JSON.parse(c));const l=localStorage.getItem(LEGACY_STORAGE_KEY);prefs=l?normalizePrefs(JSON.parse(l)):defaultPrefs();localStorage.setItem(STORAGE_KEY,JSON.stringify(prefs));return prefs;}catch(_){return prefs=defaultPrefs();}}
  function savePrefs(n){prefs=normalizePrefs(n);try{localStorage.setItem(STORAGE_KEY,JSON.stringify(prefs));}catch(_){}}
  function tableParts(){const body=document.getElementById("extensionDeviceBody"),table=body?.closest("table")||null,headerRow=table?.querySelector("thead tr")||null;return{body,table,headerRow};}
  function ensureCompactWorkerSettingsStyle(){let s=document.getElementById("chat2apiWorkerSettingsCompactV60");if(s)return s;s=document.createElement("style");s.id="chat2apiWorkerSettingsCompactV60";s.textContent='[data-worker-window-editor] [data-worker-live],[data-worker-window-editor] [data-worker-platform]{display:none!important}';document.head.appendChild(s);return s;}
  const keyedChild=(p,k)=>[...(p?.children||[])].find(n=>String(n.dataset?.chat2apiColumnKey||"")===k)||null;
  function reorder(p,a){if(!p)return;const c=[...p.children],known=a.order.map(k=>keyedChild(p,k)).filter(Boolean),unknown=c.filter(n=>!KNOWN_KEYS.has(String(n.dataset?.chat2apiColumnKey||""))),d=[...known,...unknown];if(c.length===d.length&&c.every((n,i)=>n===d[i]))return;const f=document.createDocumentFragment();for(const n of d)f.appendChild(n);p.appendChild(f);}
  function applyVisibility(p,a){if(!p)return;for(const k of a.order){const n=keyedChild(p,k);if(n)n.style.display=a.visible[k]===false?"none":"";}}
  function applyLayout(){const a=loadPrefs(),{body,headerRow}=tableParts();if(!body||!headerRow)return;reorder(headerRow,a);applyVisibility(headerRow,a);for(const tr of body.rows){if(tr.cells.length===1&&tr.cells[0].hasAttribute("colspan")){tr.cells[0].colSpan=Math.max(1,a.order.filter(k=>a.visible[k]!==false&&keyedChild(headerRow,k)).length);continue;}reorder(tr,a);applyVisibility(tr,a);}}
  function canonicalHeaderHtml(){return COLUMNS.map(({key,label})=>`<th data-chat2api-column-key="${key}"${key==="network"||key==="chatgpt"?` data-chat2api-health-column="${key}"`:""}${key==="worker_settings"?' data-chat2api-structural-owner="worker-settings-v59"':""}${key==="occupancy"?' title="当前占用 / 配置并发上限"':""}>${label}</th>`).join("");}
  function accountType(row){const v=String(row?.account_type||row?.metadata?.account_type||"unknown").trim().toLowerCase();if(v==="paid")return"plus";return["free","plus","pro"].includes(v)?v:"unknown";}
  function accountPill(row){const v=accountType(row),strategy=String(row?.metadata?.account_detection_strategy||""),confidence=String(row?.metadata?.account_detection_confidence||""),title=esc([strategy,confidence].filter(Boolean).join(" · "));if(v==="free")return`<span class="pill warn" title="${title}">Free</span>`;if(v==="plus")return`<span class="pill ok" title="${title}">Plus</span>`;if(v==="pro")return`<span class="pill ok" title="${title}">Pro</span>`;return`<span class="pill" title="${title}">未知</span>`;}
  function statusPill(r){if(r?.connection_enabled===false)return'<span class="pill">已禁用</span>';if(r?.online&&r?.busy)return'<span class="pill warn">忙碌</span>';if(r?.online)return'<span class="pill ok">在线</span>';return'<span class="pill bad">离线</span>';}
  function networkLabel(r){const m=r?.metadata||{},s=String(m.network_probe_status||"unknown"),c=String(m.network_country_code||"").trim();if(s==="external")return{text:`外网${c?` · ${c}`:""}`,cls:"ok"};if(s==="china-mainland")return{text:`中国大陆${c?` · ${c}`:""}`,cls:"warnText"};if(s==="offline")return{text:"浏览器离线",cls:"bad"};if(s==="error")return{text:"探测失败",cls:"warnText"};return{text:"未知",cls:"warnText"};}
  function chatgptLabel(r){const m=r?.metadata||{},s=String(m.chatgpt_login_state||"unknown");if(s==="ready")return{text:"已登录",cls:m.chatgpt_login_composer_ready===true?"ok":"warnText"};if(s==="login_required")return{text:"未登录",cls:"bad"};if(s==="checking")return{text:"检测中",cls:"warnText"};return{text:"未知",cls:"warnText"};}
  function occupancy(r){const c=r?.capacity&&typeof r.capacity==="object"?r.capacity:{},used=Number(c.used_units??r?.active_api_calls??0)||0,limit=Number(c.limit_units??r?.max_concurrency??r?.configured_max_concurrency??0)||0,q=Number(c.queued_requests??0)||0,cooling=c.rate_limit_cooldown_active===true,rem=Number(c.rate_limit_cooldown_remaining_seconds||0);return{text:`${used} / ${limit||"-"}${q>0?` · 排队 ${q}`:""}`,title:`当前占用 ${used}${limit?` / ${limit}`:""}${q>0?`；排队 ${q}`:""}${cooling?`；额度冷却 ${Math.max(0,Math.ceil(rem))} 秒`:""}`,cls:used>0?"warnText":"muted"};}
  function workerActions(r){const id=esc(r.client_id||""),connect=r.connection_enabled===false?`<button class="action good" data-worker-list-action="enable" data-client-id="${id}">连接</button>`:`<button class="action danger" data-worker-list-action="disconnect" data-client-id="${id}">断开</button>`;return`<div class="rowactions">${connect}<button class="action danger" data-worker-list-action="delete" data-client-id="${id}" data-online="${r.online?"1":"0"}">删除</button></div>`;}
  function rowHtml(r){const network=networkLabel(r),login=chatgptLabel(r),occupied=occupancy(r),clientId=esc(r.client_id||""),deviceName=String(r?.device_name||"").trim(),deviceNameHtml=deviceName?`<span title="${esc(r?.device_code_id||r?.pairing_id||"")}">${esc(deviceName)}</span>`:'<span class="muted">-</span>';return`<tr data-chat2api-canonical-worker-row="1" data-client-id="${clientId}"><td data-chat2api-column-key="client_id"><code>${clientId}</code></td><td data-chat2api-column-key="device_id"><code>${esc(r.device_id||r.metadata?.device_id||"-")}</code></td><td data-chat2api-column-key="version">${esc(r.metadata?.extension_version||r.version||"-")}</td><td data-chat2api-column-key="account_type">${accountPill(r)}</td><td data-chat2api-column-key="status">${statusPill(r)}</td><td data-chat2api-column-key="worker_settings" data-chat2api-structural-owner="worker-settings-v59"><span class="muted">加载中…</span></td><td data-chat2api-column-key="last_seen">${typeof fmtTime==="function"?fmtTime(r.last_seen_at):esc(r.last_seen_at||"-")}</td><td data-chat2api-column-key="network" data-chat2api-health-cell="network" class="${network.cls}">${esc(network.text)}</td><td data-chat2api-column-key="chatgpt" data-chat2api-health-cell="chatgpt" class="${login.cls}">${esc(login.text)}</td><td data-chat2api-column-key="actions">${workerActions(r)}</td><td data-chat2api-column-key="device_name">${deviceNameHtml}</td><td data-chat2api-column-key="occupancy" class="${occupied.cls}" title="${esc(occupied.title)}">${esc(occupied.text)}</td></tr>`;}
  function renderWorkerRows(rows){const{body,headerRow,table}=tableParts();if(!body||!headerRow)return;canonicalizing=true;try{const h=canonicalHeaderHtml();if(headerRow.innerHTML!==h)headerRow.innerHTML=h;body.innerHTML=rows.length?rows.map(rowHtml).join(""):`<tr><td colspan="${COLUMNS.length}" class="muted">暂无 Worker。</td></tr>`;applyLayout();document.documentElement.dataset.chat2apiWorkerListReady="1";document.documentElement.dataset.chat2apiWorkerListVersion=VERSION;document.documentElement.dataset.chat2apiWorkerColumnSchemaRevision=String(COLUMN_SCHEMA_REVISION);if(table)table.style.visibility="";}finally{canonicalizing=false;}}
  function pairingState(r){const p=(r.pairing_status||(r.bound_client_id?"paired":"unpaired"))==="paired";return`<span class="pill ${p?"ok":"warn"}">${p?"已配对":"未配对"}</span>`;}
  function renderPairings(rows){const b=document.getElementById("pairingBody");if(!b)return;b.innerHTML=rows.length?rows.map(r=>`<tr><td>${esc(r.name)}</td><td><code>${esc(r.prefix||"-")}</code></td><td><code>${esc(r.bound_client_id||"-")}</code></td><td><code>${esc(r.bound_device_id||"-")}</code></td><td>${pairingState(r)}</td><td>${typeof fmtTime==="function"?fmtTime(r.last_paired_at):esc(r.last_paired_at||"-")}</td><td><div class="rowactions"><button class="action" data-pairing-list-action="copy" data-pairing-id="${esc(r.pairing_id)}">复制</button><button class="action" data-pairing-list-action="toggle" data-pairing-id="${esc(r.pairing_id)}" data-enable="${r.enabled?"0":"1"}">${r.enabled?"停用":"启用"}</button><button class="action danger" data-pairing-list-action="delete" data-pairing-id="${esc(r.pairing_id)}">删除</button></div></td></tr>`).join(""):'<tr><td colspan="7">暂无配对码，请先创建。</td></tr>';}
  async function loadCanonicalExtensions(force=false){if(renderInFlight&&!force)return renderInFlight;const task=(async()=>{try{const d=await api("/api/admin/extensions");extensionSnapshot=Array.isArray(d.clients)?d.clients:[];renderPairings(Array.isArray(d.pairing_codes)?d.pairing_codes:[]);renderWorkerRows(extensionSnapshot);return d;}catch(e){const{table}=tableParts();if(table)table.style.visibility="";if(typeof globalThis.status==="function")status("Worker 列表加载失败："+String(e?.message||e),"bad");throw e;}})();renderInFlight=task;try{return await task;}finally{if(renderInFlight===task)renderInFlight=null;}}
  function isCanonical(){const{body,headerRow}=tableParts();if(!body||!headerRow)return true;const h=[...headerRow.children].filter(n=>KNOWN_KEYS.has(String(n.dataset?.chat2apiColumnKey||"")));if(h.length!==COLUMNS.length)return false;for(const tr of body.rows){if(tr.cells.length===1&&tr.cells[0].hasAttribute("colspan"))continue;if(!tr.dataset.chat2apiCanonicalWorkerRow)return false;if(!DEFAULT_ORDER.every(k=>Boolean(keyedChild(tr,k))))return false;}return true;}
  function queueCanonicalRepair(){if(canonicalizing||repairQueued||!extensionSnapshot)return;repairQueued=true;queueMicrotask(()=>{repairQueued=false;if(!canonicalizing&&!isCanonical()&&extensionSnapshot)renderWorkerRows(extensionSnapshot);});}
  function observeLegacyRebuilds(){const{body,headerRow}=tableParts();if(typeof MutationObserver!=="function")return;if(body)new MutationObserver(queueCanonicalRepair).observe(body,{childList:true});if(headerRow)new MutationObserver(queueCanonicalRepair).observe(headerRow,{childList:true});}
  function activateExtensionView(){document.querySelectorAll(".view").forEach(n=>n.classList.remove("active"));document.querySelectorAll(".nav button").forEach(n=>n.classList.toggle("active",n.dataset.view==="extensions"));document.getElementById("view-extensions")?.classList.add("active");const p=document.getElementById("pageTitle");if(p)p.textContent="Worker管理";if(location.hash!=="#extensions")location.hash="extensions";}
  function installCanonicalShowOwner(){const base=typeof globalThis.show==="function"?globalThis.show:null;if(!base||base.__chat2apiCanonicalWorkerListV59)return;const w=async v=>{if(v!=="extensions")return base(v);const g=document.getElementById("adminLoginGate");if(g&&g.style.display!=="none")return;activateExtensionView();return loadCanonicalExtensions(true);};w.__chat2apiCanonicalWorkerListV59=true;globalThis.show=w;}
  function ensureSettingsButton(){const b=document.getElementById("extensionDeviceBody"),p=b?.closest(".panel"),h=p?.querySelector("h3");if(!h)return null;h.textContent="Worker列表";let x=document.getElementById("extensionColumnSettingsButton");if(!x){x=document.createElement("button");x.id="extensionColumnSettingsButton";x.className="action";x.textContent="⚙";x.title="Worker列表列设置";x.style.marginLeft="8px";h.appendChild(x);}return x;}
  function ensureMenu(){let b=document.getElementById("extensionColumnSettingsBackdrop");if(!b){b=document.createElement("div");b.id="extensionColumnSettingsBackdrop";b.style.cssText="position:fixed;inset:0;z-index:300;display:none;align-items:center;justify-content:center;padding:24px;background:rgba(2,6,23,.72);backdrop-filter:blur(2px)";b.addEventListener("mousedown",e=>{if(e.target===b)closeMenu();});document.body.appendChild(b);}let m=document.getElementById("extensionColumnSettingsMenu");if(!m){m=document.createElement("div");m.id="extensionColumnSettingsMenu";m.tabIndex=-1;m.style.cssText="width:min(980px,calc(100vw - 48px));max-height:min(82vh,760px);display:flex;flex-direction:column;overflow:hidden;border:1px solid rgba(148,163,184,.28);border-radius:16px;background:#0f172a;box-shadow:0 28px 90px rgba(0,0,0,.55)";m.addEventListener("mousedown",e=>e.stopPropagation());b.appendChild(m);}return m;}
  function closeMenu(){const b=document.getElementById("extensionColumnSettingsBackdrop");if(b)b.style.display="none";if(menuOpen)document.body.style.overflow=bodyOverflowBeforeModal;menuOpen=false;}
  function moveColumn(k,d){const a=structuredClone(loadPrefs()),i=a.order.indexOf(k),n=i+d;if(i<0||n<0||n>=a.order.length)return;[a.order[i],a.order[n]]=[a.order[n],a.order[i]];savePrefs(a);applyLayout();renderMenu();}
  function setVisible(k,v){const a=structuredClone(loadPrefs());a.visible[k]=Boolean(v);savePrefs(a);applyLayout();renderMenu();}
  function renderMenu(){const m=ensureMenu(),a=loadPrefs(),labels=new Map(COLUMNS.map(x=>[x.key,x.label])),count=a.order.filter(k=>a.visible[k]!==false).length,cards=a.order.map((k,i)=>`<div style="display:flex;flex-direction:column;gap:10px;min-width:0;padding:12px;border:1px solid rgba(148,163,184,.16);border-radius:11px;background:rgba(15,23,42,.72)"><div style="display:flex;align-items:center;gap:9px"><span style="min-width:30px;padding:3px 6px;text-align:center;border-radius:999px;background:rgba(59,130,246,.16);color:#93c5fd;font-size:11px">${String(i+1).padStart(2,"0")}</span><label style="display:flex;align-items:center;gap:8px;flex:1;font-weight:600"><input type="checkbox" data-column-visible="${k}" ${a.visible[k]!==false?"checked":""}><span>${esc(labels.get(k)||k)}</span></label></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px"><button class="action" data-column-move="${k}" data-delta="-1" ${i===0?"disabled":""}>← 前移</button><button class="action" data-column-move="${k}" data-delta="1" ${i===a.order.length-1?"disabled":""}>后移 →</button></div></div>`).join("");m.innerHTML=`<div style="display:flex;justify-content:space-between;gap:16px;padding:18px 20px 14px;border-bottom:1px solid rgba(148,163,184,.16)"><div><div style="font-size:17px;font-weight:700">Worker列表列设置</div></div><div style="display:flex;gap:8px"><button class="action" data-reset-columns>恢复默认</button><button class="action" data-close-columns>✕</button></div></div><div class="muted" style="padding:10px 20px 0;font-size:12px">已显示 ${count} / ${a.order.length} 列</div><div style="overflow:auto;padding:14px 20px 18px"><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:10px">${cards}</div></div>`;}
  function openMenu(){ensureMenu();renderMenu();if(!menuOpen)bodyOverflowBeforeModal=document.body.style.overflow;menuOpen=true;document.body.style.overflow="hidden";const b=document.getElementById("extensionColumnSettingsBackdrop");if(b)b.style.display="flex";}
  async function pairingAction(button){const a=button.dataset.pairingListAction||"",id=button.dataset.pairingId||"";if(!id)return;if(a==="copy"){const d=await api(`/api/admin/pairing-codes/${encodeURIComponent(id)}/secret`);await navigator.clipboard.writeText(d.code||"");if(d.rotated)await loadCanonicalExtensions(true);return;}if(a==="toggle"){await api(`/api/admin/pairing-codes/${encodeURIComponent(id)}`,{method:"PATCH",body:{enabled:button.dataset.enable==="1"}});await loadCanonicalExtensions(true);return;}if(a==="delete"&&confirm("确定删除这个配对码？")){await api(`/api/admin/pairing-codes/${encodeURIComponent(id)}`,{method:"DELETE"});await loadCanonicalExtensions(true);}}
  async function workerAction(button){const a=button.dataset.workerListAction||"",id=button.dataset.clientId||"";if(!id)return;if(a==="disconnect")await api(`/api/admin/extensions/${encodeURIComponent(id)}/connection`,{method:"PATCH",body:{enabled:false}});else if(a==="enable")await api(`/api/admin/extensions/${encodeURIComponent(id)}/connection`,{method:"PATCH",body:{enabled:true}});else if(a==="delete"){if(button.dataset.online==="1"&&!confirm("Worker 当前在线，确定删除？"))return;await api(`/api/admin/extensions/${encodeURIComponent(id)}`,{method:"DELETE"});}await loadCanonicalExtensions(true);}
  function bindEvents(){document.addEventListener("click",async e=>{const s=e.target.closest?.("#extensionColumnSettingsButton");if(s){openMenu();return;}const close=e.target.closest?.("[data-close-columns]");if(close){closeMenu();return;}const reset=e.target.closest?.("[data-reset-columns]");if(reset){savePrefs(defaultPrefs());applyLayout();renderMenu();return;}const move=e.target.closest?.("[data-column-move]");if(move){moveColumn(move.dataset.columnMove,Number(move.dataset.delta||0));return;}const pa=e.target.closest?.("[data-pairing-list-action]");if(pa){await pairingAction(pa);return;}const wa=e.target.closest?.("[data-worker-list-action]");if(wa){await workerAction(wa);return;}},true);document.addEventListener("change",e=>{const x=e.target.closest?.("[data-column-visible]");if(x)setVisible(x.dataset.columnVisible,x.checked);},true);}
  function start(){ensureCompactWorkerSettingsStyle();ensureSettingsButton();installCanonicalShowOwner();observeLegacyRebuilds();bindEvents();if(location.hash==="#extensions"||document.getElementById("view-extensions")?.classList.contains("active"))loadCanonicalExtensions(true).catch(()=>{});}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",start,{once:true});else start();
})();
