from .main import app
from .voice_patch import install_voice_patch
from .live_voice_patch import install_live_voice_patch
from .v7_patch import install_v7_patch
from .v8_patch import install_v8_patch
from .v9_patch import install_v9_patch
from .v10_patch import install_v10_patch
from .v11_patch import install_v11_patch
from .v12_patch import install_v12_patch
from .v13_patch import install_v13_patch
from .v14_patch import install_v14_patch
from .v15_patch import install_v15_patch
from .v16_patch import install_v16_patch
from .v17_patch import install_v17_patch
from .v17_crypto_patch import install_v17_crypto_patch
from .v17_route_migration_patch import install_v17_route_migration_patch
from .v17_finalize_patch import install_v17_finalize_patch
from .v17_1_patch import install_v17_1_patch
from .v18_patch import install_v18_patch
from .v19_patch import install_v19_patch
from .v20_patch import install_v20_patch
from .v20_1_patch import install_v20_1_patch
from .v20_2_patch import install_v20_2_patch
from .v20_3_patch import install_v20_3_patch
from .v21_patch import install_v21_patch
from .v21_routing_patch import install_v21_routing_patch
from .v21_1_patch import install_v21_1_patch
from .v21_2_patch import install_v21_2_patch
from .v21_3_patch import install_v21_3_patch
from .v21_4_model_contract_patch import install_v21_4_model_contract_patch
from .v21_5_patch import install_v21_5_patch
from .v21_6_patch import install_v21_6_patch
from .v21_13_patch import install_v21_13_patch
from .linux_worker_patch import install_linux_worker_patch
from .linux_worker_login_freshness_patch import install_linux_worker_login_freshness_patch
from .linux_worker_install_patch import install_linux_worker_install_patch
from .linux_worker_xray_patch import install_linux_worker_xray_patch
from .linux_worker_bridge_binding import install_linux_worker_bridge_binding_patch
from .linux_worker_ui_state_patch import install_linux_worker_ui_state_patch
from .linux_worker_proxy_catalog_patch import install_linux_worker_proxy_catalog_patch
from .linux_worker_pairing_patch import install_linux_worker_pairing_patch
from .linux_worker_proxy_name_patch import install_linux_worker_proxy_name_patch
from .linux_worker_table_stability_patch import install_linux_worker_table_stability_patch
from .linux_worker_install_ux_patch import install_linux_worker_install_ux_patch
from .linux_worker_repair_command_patch import install_linux_worker_repair_command_patch
from .linux_worker_diagnostics_patch import install_linux_worker_diagnostics_patch
from .linux_worker_initialize_patch import install_linux_worker_initialize_patch
from .linux_worker_upgrade_patch import install_linux_worker_upgrade_patch
from .linux_worker_enable_patch import install_linux_worker_enable_patch
from .linux_worker_console_polling_patch import install_linux_worker_console_polling_patch
from .stream_keepalive_patch import install_stream_keepalive_patch
from .request_stall_patch import install_request_stall_patch
from .request_recovery_patch import install_request_recovery_patch
from .worker_transport_recovery_patch import install_worker_transport_recovery_patch
from .request_device_identity_patch import install_request_device_identity_patch
from .window_manager_v88_patch import install_window_manager_v88_patch
from .playground_lifecycle_patch import install_playground_lifecycle_patch
from .playground_multimodal_defaults_patch import install_playground_multimodal_defaults_patch
from .playground_random_prompt_patch import install_playground_random_prompt_patch
from .playground_chat_patch import install_playground_chat_patch
from .runtime_contract import install_runtime_contract
from .runtime_logs_patch import install_runtime_logs_patch
from .extension_capacity_control_patch import install_extension_capacity_control_patch
from .mini_multimodal_quota_patch import install_mini_multimodal_quota_patch
from .model_capability_routing_patch import install_model_capability_routing_patch
from .account_generation_admission_patch import install_account_generation_admission_patch
from .generation_backend_routing_patch import install_generation_backend_routing_patch
from .server_update_patch import install_server_update_patch
from .server_worker_sync_lifespan_patch import install_server_worker_sync_patch
from .worker_disable_authority_patch import install_worker_disable_authority_patch
from .worker_presentation_v64_patch import install_worker_presentation_v64_patch
from .api_key_console_v68_patch import install_api_key_console_v68_patch
from .rich_response_docs_patch import install_rich_response_docs_patch
from .prompt_config_v72_patch import install_prompt_config_v72_patch
from .attachment_download_v82_patch import install_attachment_download_v82_patch
from .request_history_v94_patch import install_request_history_v94_patch
from .user_console_v104_patch import install_user_console_v104_patch
from .user_console_privacy_v105_patch import install_user_console_privacy_v105_patch
from .payment_channels_v106_patch import install_payment_channels_v106_patch
from .payment_channels_v107_safety_patch import install_payment_channels_v107_safety_patch
from .responses_v108_patch import install_responses_v108_patch
from .responses_model_routing_v108_patch import install_responses_model_routing_v108_patch
from .responses_console_v110_patch import install_responses_console_v110_patch
from .request_id_namespace_v136_patch import install_request_id_namespace_v136_patch
from .worker_limits_clipboard_v121_patch import install_worker_limits_clipboard_v121_patch
from .model_observability_v144_patch import install_model_observability_v144_patch

install_voice_patch(app)
install_live_voice_patch(app)
install_v7_patch(app)
install_v8_patch(app)
install_v9_patch(app)
install_v10_patch(app)
install_v11_patch(app)
install_v12_patch(app)
install_v13_patch(app)
install_v14_patch(app)
install_v15_patch(app)
install_v16_patch(app)
install_v17_patch(app)
install_v17_crypto_patch(app)
install_v17_route_migration_patch(app)
install_v17_finalize_patch(app)
install_v17_1_patch(app)
install_v18_patch(app)
install_v19_patch(app)
install_v20_patch(app)
install_v20_1_patch(app)
install_v20_2_patch(app)
install_v20_3_patch(app)
install_v21_patch(app)
install_v21_routing_patch(app)
install_v21_1_patch(app)
install_v21_2_patch(app)
install_v21_3_patch(app)
install_v21_4_model_contract_patch(app)
install_v21_5_patch(app)
install_v21_6_patch(app)
install_v21_13_patch(app)
install_linux_worker_patch(app)
install_linux_worker_login_freshness_patch(app)
install_linux_worker_install_patch(app)
install_linux_worker_xray_patch(app)
install_linux_worker_bridge_binding_patch(app)
install_linux_worker_ui_state_patch(app)
install_linux_worker_proxy_catalog_patch(app)
install_stream_keepalive_patch(app)
install_request_stall_patch(app)
install_request_recovery_patch(app)
install_worker_transport_recovery_patch(app)
install_playground_lifecycle_patch(app)
install_playground_multimodal_defaults_patch(app)
install_playground_random_prompt_patch(app)
install_playground_chat_patch(app)
install_runtime_contract(app)
install_runtime_logs_patch(app)
install_extension_capacity_control_patch(app)
install_mini_multimodal_quota_patch(app)
install_linux_worker_pairing_patch(app)
install_linux_worker_proxy_name_patch(app)
install_linux_worker_table_stability_patch(app)
install_linux_worker_install_ux_patch(app)
install_linux_worker_repair_command_patch(app)
install_linux_worker_diagnostics_patch(app)
install_linux_worker_initialize_patch(app)
install_linux_worker_upgrade_patch(app)
install_linux_worker_enable_patch(app)
install_model_capability_routing_patch(app)
install_account_generation_admission_patch(app)
install_generation_backend_routing_patch(app)
install_linux_worker_console_polling_patch(app)
install_request_device_identity_patch(app)
install_window_manager_v88_patch(app)
install_server_update_patch(app)
install_server_worker_sync_patch(app)
install_worker_disable_authority_patch(app)
install_worker_presentation_v64_patch(app)
install_api_key_console_v68_patch(app)
install_rich_response_docs_patch(app)
install_attachment_download_v82_patch(app)
install_prompt_config_v72_patch(app)
install_request_history_v94_patch(app)
install_user_console_v104_patch(app)
install_payment_channels_v106_patch(app)
install_payment_channels_v107_safety_patch(app)
install_user_console_privacy_v105_patch(app)
install_responses_model_routing_v108_patch(app)
install_responses_v108_patch(app)
install_responses_console_v110_patch(app)
install_request_id_namespace_v136_patch(app)
install_worker_limits_clipboard_v121_patch(app)
install_request_history_v94_patch(app)
# v144 is the final model authority/observability boundary. It is deliberately
# installed after the canonical request-history renderer and every historical
# routing patch, so downstream code cannot silently redefine the selected model.
install_model_observability_v144_patch(app)
