from __future__ import annotations

import asyncio
import secrets
from pathlib import Path
from typing import Any

from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import Response

from .admin_auth import SESSION_COOKIE


PATCH_REVISION = 88
LIVE_TRUTH_REVISION = 89
LIVE_TRUTH_MIN_BUNDLE = (0, 8, 27)
LIVE_TRUTH_TIMEOUT_SECONDS = 1.2
ADMIN_ASSET = "/assets/chat2api-window-manager-v88.js"


async def _response_bytes(response: Response) -> bytes:
    body = getattr(response, "body", None)
    if body is not None:
        return bytes(body)
    chunks: list[bytes] = []
    iterator = getattr(response, "body_iterator", None)
    if iterator is not None:
        async for chunk in iterator:
            chunks.append(chunk.encode() if isinstance(chunk, str) else bytes(chunk))
    return b"".join(chunks)


def _version_tuple(value: Any) -> tuple[int, int, int]:
    parts: list[int] = []
    for raw in str(value or "").strip().lstrip("v").split(".")[:3]:
        digits = "".join(ch for ch in raw if ch.isdigit())
        parts.append(int(digits or 0))
    while len(parts) < 3:
        parts.append(0)
    return tuple(parts[:3])  # type: ignore[return-value]


def _worker_bundle_version(summary: dict[str, Any]) -> str:
    metadata = summary.get("metadata") if isinstance(summary.get("metadata"), dict) else {}
    return str(metadata.get("extension_version") or summary.get("version") or "")


def _snapshot(summary: dict[str, Any]) -> dict[str, Any]:
    metadata = summary.get("metadata") if isinstance(summary.get("metadata"), dict) else {}
    value = metadata.get("window_manager_v88")
    return value if isinstance(value, dict) else {}


def _snapshot_updated_at(summary: dict[str, Any]) -> int:
    try:
        return int(_snapshot(summary).get("updated_at_ms") or 0)
    except (TypeError, ValueError):
        return 0


def install_window_manager_v88_patch(app: FastAPI) -> FastAPI:
    """Expose Worker browser-window truth to administrators.

    v88 introduced the Worker-owned window registry. v89 hardens the read side:
    an administrator view must no longer treat a persisted Worker snapshot as a
    live Chrome window. Workers on bundle 0.8.27+ are asked to reconcile against
    ``chrome.windows.getAll({populate:true})`` before their active rows are
    returned. Older/offline Workers remain visible as unverified telemetry, but
    cached active rows are deliberately excluded from the live table.
    """
    if getattr(app.state, "window_manager_v88_installed", False):
        return app
    app.state.window_manager_v88_installed = True

    registry = app.state.registry
    sessions = app.state.admin_sessions

    def require_admin(request: Request) -> None:
        if not sessions.authenticate(request.cookies.get(SESSION_COOKIE)):
            raise HTTPException(status_code=401, detail="Administrator login required")

    async def refresh_live_truth() -> tuple[set[str], set[str]]:
        """Demand a physical Chrome reconciliation and wait for fresh telemetry.

        ``updated_at_ms`` is generated by the Worker at report time. Requiring it
        to advance after our control message prevents a three-hour-old snapshot
        from being presented as a current physical window merely because the
        Worker is still online.
        """
        summaries = registry.summaries()
        before: dict[str, int] = {}
        attempted: set[str] = set()

        for summary in summaries:
            client_id = str(summary.get("client_id") or "")
            if not client_id or not bool(summary.get("online")):
                continue
            if _version_tuple(_worker_bundle_version(summary)) < LIVE_TRUTH_MIN_BUNDLE:
                continue
            before[client_id] = _snapshot_updated_at(summary)
            control_id = "window_refresh_" + secrets.token_urlsafe(8).replace("-", "").replace("_", "")
            try:
                await registry.send(client_id, {
                    "type": "window.manager.refresh",
                    "control_id": control_id,
                    "reason": "admin-window-manager-live-truth-v89",
                    "revision": LIVE_TRUTH_REVISION,
                })
                attempted.add(client_id)
            except RuntimeError:
                continue

        if not attempted:
            return set(), attempted

        verified: set[str] = set()
        loop = asyncio.get_running_loop()
        deadline = loop.time() + LIVE_TRUTH_TIMEOUT_SECONDS
        while loop.time() < deadline:
            current = {str(row.get("client_id") or ""): row for row in registry.summaries()}
            for client_id in attempted - verified:
                row = current.get(client_id)
                if not row or not bool(row.get("online")):
                    continue
                if _snapshot_updated_at(row) > before.get(client_id, 0):
                    verified.add(client_id)
            if verified == attempted:
                break
            await asyncio.sleep(0.04)
        return verified, attempted

    def window_rows(verified: set[str], attempted: set[str]) -> dict[str, Any]:
        active: list[dict[str, Any]] = []
        closed: list[dict[str, Any]] = []
        workers: list[dict[str, Any]] = []
        for summary in registry.summaries():
            row = dict(summary)
            metadata = row.get("metadata") if isinstance(row.get("metadata"), dict) else {}
            snapshot = _snapshot(row)
            client_id = str(row.get("client_id") or "")
            device_name = str(row.get("device_name") or metadata.get("device_name") or row.get("name") or "").strip() or None
            device_code_id = str(row.get("device_code_id") or row.get("pairing_id") or metadata.get("pairing_id") or "").strip() or None
            bundle_version = _worker_bundle_version(row)
            online = bool(row.get("online"))
            refresh_capable = _version_tuple(bundle_version) >= LIVE_TRUTH_MIN_BUNDLE
            live_verified = client_id in verified
            cached_active = [item for item in (snapshot.get("active") or []) if isinstance(item, dict)]
            if live_verified:
                truth_status = "verified"
            elif not online:
                truth_status = "offline"
            elif not refresh_capable:
                truth_status = "upgrade-required"
            elif client_id in attempted:
                truth_status = "refresh-timeout"
            else:
                truth_status = "unverified"

            workers.append({
                "client_id": client_id,
                "device_name": device_name,
                "device_code_id": device_code_id,
                "online": online,
                "bundle_version": bundle_version,
                "window_manager_revision": metadata.get("window_manager_revision"),
                "window_selection_policy": metadata.get("window_selection_policy"),
                "snapshot_updated_at_ms": snapshot.get("updated_at_ms"),
                "cached_active_count": len(cached_active),
                "live_verified": live_verified,
                "truth_status": truth_status,
                "truth_revision": LIVE_TRUTH_REVISION,
            })

            # Critical truth boundary: only the snapshot produced in response to
            # this administrator refresh is allowed into "接待中窗口". Persisted
            # rows from an old Worker session are historical telemetry, not proof
            # that a Chrome window still exists now.
            if live_verified:
                for raw in cached_active:
                    item = dict(raw)
                    item.update({
                        "client_id": client_id,
                        "device_name": device_name,
                        "device_code_id": device_code_id,
                        "worker_online": online,
                        "live_verified": True,
                    })
                    active.append(item)

            for raw in snapshot.get("closed") or []:
                if not isinstance(raw, dict):
                    continue
                item = dict(raw)
                item.update({
                    "client_id": client_id,
                    "device_name": device_name,
                    "device_code_id": device_code_id,
                    "worker_online": online,
                })
                closed.append(item)

        active.sort(key=lambda item: (int(item.get("window_no") or 10**9), int(item.get("opened_at_ms") or 10**18)))
        closed.sort(key=lambda item: int(item.get("closed_at_ms") or 0), reverse=True)
        unverified = [row for row in workers if row.get("online") and not row.get("live_verified")]
        return {
            "revision": PATCH_REVISION,
            "truth_revision": LIVE_TRUTH_REVISION,
            "policy": "oldest-ready-fifo-v88",
            "active": active,
            "closed": closed,
            "workers": workers,
            "truth": {
                "verified_workers": sum(1 for row in workers if row.get("live_verified")),
                "online_workers": sum(1 for row in workers if row.get("online")),
                "unverified_workers": len(unverified),
                "cached_active_rows_suppressed": sum(int(row.get("cached_active_count") or 0) for row in unverified),
            },
        }

    @app.get("/api/admin/window-manager")
    async def admin_window_manager(request: Request) -> dict[str, Any]:
        require_admin(request)
        verified, attempted = await refresh_live_truth()
        return window_rows(verified, attempted)

    @app.post("/api/admin/window-manager/{client_id}/{window_id}/capture")
    async def admin_capture_window(client_id: str, window_id: int, request: Request) -> dict[str, Any]:
        require_admin(request)
        if client_id not in registry.clients:
            raise HTTPException(status_code=404, detail="Unknown Worker")
        if client_id not in registry.sockets:
            raise HTTPException(status_code=409, detail="Worker is offline")
        control_id = "window_" + secrets.token_urlsafe(9).replace("-", "").replace("_", "")
        try:
            await registry.send(client_id, {
                "type": "window.manager.capture",
                "control_id": control_id,
                "window_id": int(window_id),
            })
        except RuntimeError as error:
            raise HTTPException(status_code=409, detail=str(error)) from error
        return {
            "accepted": True,
            "control_id": control_id,
            "client_id": client_id,
            "window_id": int(window_id),
            "revision": PATCH_REVISION,
        }

    @app.get(ADMIN_ASSET, include_in_schema=False)
    async def window_manager_asset() -> Response:
        path = Path(__file__).with_name("admin_window_manager_v88.js")
        return Response(
            path.read_text(encoding="utf-8"),
            media_type="application/javascript",
            headers={"Cache-Control": "no-store, no-cache, must-revalidate"},
        )

    @app.middleware("http")
    async def inject_window_manager(request: Request, call_next):
        response = await call_next(request)
        if request.url.path != "/admin" or "text/html" not in response.headers.get("content-type", ""):
            return response
        raw = await _response_bytes(response)
        text = raw.decode("utf-8", errors="replace")
        marker = f'<script src="{ADMIN_ASSET}"></script>'
        if marker not in text:
            text = text.replace("</body>", marker + "</body>")
        headers = {
            key: value
            for key, value in response.headers.items()
            if key.lower() not in {"content-length", "content-type"}
        }
        headers["Cache-Control"] = "no-store, no-cache, must-revalidate"
        return Response(text, status_code=response.status_code, media_type="text/html", headers=headers)

    return app
